name: CharmRealm
main: com.SelfHome.Main
author: Caizii
version: 2.1.2.3
softdepend: [PlaceholderAPI,Vault,Multiverse-Core,FastAsyncWorldEdit,WorldEdit,NBTAPI,PlayerPoints,HolographicDisplays,ProtocolLib,RealisticSeasons]
commands: 
  realm:
    description: example
    permission-message: You don't have permission use this Commands