name: ${name}
main: com.caizii.charmrealm.CharmRealm
author: [ Caizii ]
version: ${version}
api-version: "1.16"
depend: [ ProtocolLib,PlaceholderAPI ]
softdepend: [ Vault,Multiverse-Core,FastAsyncWorldEdit,WorldEdit,NBTAPI,PlayerPoints,HolographicDisplays,RealisticSeasons ]
commands:
  realm:
    description: Realm related command that create, modify and delete realms.
    permission-message: You don't have permission use this Commands