name: SelfHomeMain
main: com.SelfHome.Main
author: a1242839141, Caizii
version: 2.0.2.9
softdepend: [PlaceholderAPI,Vault,Multiverse-Core,FastAsyncWorldEdit,WorldEdit,NBTAPI,PlayerPoints,HolographicDisplays,ProtocolLib,RealisticSeasons]
commands: 
  SH:
    description: example
    permission-message: You don't have permission use this Commands
  realm:
    description: 领域相关指令
    permission-message: You don't have permission use this Commands